[project]
name = "lab-semana1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Leny Tacuri", email = "lenytacuri1995@hotmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.4",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.uv]
package = false